SELECT * FROM SCOTT.emp;
/*
 ASSIGNMENT 4:OPERATORS
   1) LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL.
   2) LIST ALL THE EMPLOYEES WHO DON’T HAVE A REPORTING MANAGER.
   3) LIST ALL THE SALESMEN IN DEPT 30.
   4) LIST ALL THE SALESMEN IN DEPT NUMBER 30 AND HAVING SALARY GREATER THAN 1500.
   5) LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH ‘S’ OR ‘A’.
   6) LIST ALL THE EMPLOYEES EXCEPT THOSE WHO ARE WORKING IN DEPT 10 & 20.
   7) LIST THE EMPLOYEES WHOSE NAME DOES NOT START WITH ‘S’.
   8) LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10.
   9) LIST ALL THE EMPLOYEES WHOSE COMMISSION IS NULL AND WORKING AS CLERK.
   10) LIST ALL THE EMPLOYEES WHO DON’T HAVE A REPORTING MANAGER IN DEPTNO 10 OR 30.
   
   11) LIST ALL THE SALESMEN IN DEPT 30 WITH SAL MORE THAN 2450.
   12) LIST ALL THE ANALYST IN DEPT NUMBER 20 AND HAVING SALARY GREATER THAN 2500.
   13) LIST ALL THE EMPLOYEES WHOSE NAME STARTS WITH ‘M’ OR ‘J’.
   14) LIST ALL THE EMPLOYEES WITH ANNUAL SALARY EXCEPT THOSE WHO ARE WORKING IN DEPT 30.
   15) LIST THE EMPLOYEES WHOSE NAME DOES NOT END WITH ‘E’ OR ‘R’.
   16) LIST ALL THE EMPLOYEES WHO ARE HAVING REPORTING MANAGERS IN DEPT 10 ALONG WITH 10% HIKE IN SALARY.
   17) DISPLAY ALL THE EMPLOYEE WHO ARE SALESMAN HAVING ‘E’ AS THE LAST CHARACTER IN ENAME AND SALARY HAVING EXACTLY 4 CHARACTER.
   18) DISPLAY ALL THE EMPLOYEE WHO ARE JOINED AFTER YEAR 81.
   19) DISPLAY ALL THE EMPLOYEE WHO ARE JOINED IN FEB.
   20) LIST THE EMPLOYEES WHO ARE NOT WORKING AS MANAGERS AND CLERKS IN DEPT 10 AND 20 WITH A SALARY IN THE RANGE OF 1000 TO 3000.
   
   21) LIST THE EMPLOYEES WHOSE SALARY NOT IN THE RANGE OF 1000 TO 2000 AND WORKING IN DEPT 10,20 OR 30 EXCEPT ALL SALESMEN.
   22) LIST THE DEPARTMENT NAMES WHICH ARE HAVING LETTER ‘O’ IN THEIR LOCATIONS AS WELL AS THEIR DEPARTMENT NAMES
   23) DISPLAY ALL THE EMPLOYEES WHOSE JOB HAS STRING ‘MAN’ IN IT.
   24)LIST THE EMPLOYEES WHO ARE HIRED AFTER 82 AND BEFORE 87.
   25)WAQTD ALL THE DETAILS OF EMPLOYEES HIRED IN NOVEMBER AND DECEMBER.
   26)LIST ALL THE EMPLOYEE NAMES AND COMISSION FOR THOSE EMPLOYEES WHO EARN COMISSION MORE THAN THEIR SALARY.
   27)WAQTD NAME AND DESIGNATION FOR ALL THE EMPLOYEES HAVING REPORTING MANAGERS AND ALSO THEIR NAMES STARTING WITH ‘S’.
   28)WAQTD NAME AND SALARY OF ALL THE EMPLOYEES IF THEIR ANNUAL SALARY ENDS WITH ‘0’ .
   29)WAQTD NAME OF THE EMPLOYEE HAVING ATLEAST 2 L’s IN HIS NAME .
   30)WAQTD NAME OF THE EMPLOYEES WHOS NAME STARTS WITH A ‘VOWEL’.
   
   31)WAQTD NAME OF THE EMPLOYEE WHOSE NAME START’S WITH ‘A’ AND IS OF LENGTH 4 CHARACTERS.
   32) WAQTD NAME OF THE EMPLOYEE WHOSE SALARY IS OF EXACTLY 5 DIGITS.
   33) WAQTD NAME OF THE EMPLOYEE WHOSE NAME IS HAVING SUBSTRING ‘NA’ ATLEAST TWICE.
   34) WAQTD NAME OF THE EMPLOYEE’S ALONG WITH SALARY,COMMISSION WHO ARE GETTING SOME COMMISSION AND COMMISSION IS OF 3 DIGIT.
   35) WAQTD WHO ARE HAVING % AS SECOND CHARACTER IN THEIR NAME.
   36) WAQTD ALL THE EMPLOYEES WHO ARE JOINED COMPANY IN 1985 AND SALARY IS LESS THAN 1000 AND GREATER THAN EQUAL TO 3000.
   37) WAQTD ALL THE EMPLOYEES WHO ARE NOT GETTING COMMISSION AND HAS LETTER ‘M’ AS SECOND LAST IN IT.
   38) WAQTD ALL THE EMPLOYEES WHO ARE NOT WORKING AS SALESMAN ,CLERK AND SALARY IS GREATER THAN EQUAL TO 1000 AND LESS THAN 4000.
   39) WAQTD ALL THE EMPLOYEES WHO ARE JOINED THE COMAPANY IN THE MONTH OF JULY.
   40) WAQTD ALL THE EMPLOYESS WHO BELONG TO DEPARTMENT 10,20,30 AND WERE HIRED DURING 1982 TO 1985.
   
   41) WAQTD NAME OF THE EMPLOYEE WHOSE NAME IS HAVING LETTER ‘P’ IN THE 4TH POSITION.
   42) WAQTD ALL THE EMPLOYEES WHOSE NAME DON’T START WITH S AND COMMISSION IS GREATER THAN 250 AND LESS THAN 1000.
   43) WAQTD ALL THE EMPLOYEES WHO ARE NOT GETTING COMMISSION AND HAS LETTER ‘M’ AS SECOND LAST IN IT.
   44) WAQTD ALL THE EMPLOYEES WHO DEPARTMENT IS 10,20,40 AND SALARY IS GREATER THAN 2000 AND LESS THAN OR EQUAL TO 4000.
   45) WAQTD ALL THE EMPLOYEES WHOSE JOB STARTS ‘CLE’ AND DEPARTMENT IS 10 OR 30.
 
 */
 
 SELECT * FROM EMP WHERE COMM IS NOT NULL;
 SELECT * FROM EMP WHERE MGR IS NULL;
 SELECT * FROM EMP WHERE JOB = 'SALESMAN' AND DEPTNO = 30;
 SELECT * FROM EMP WHERE JOB = 'SALESMAN' AND DEPTNO = 30 AND SAL > 1500;
 SELECT * FROM EMP WHERE ENAME LIKE 'S%' OR ENAME LIKE 'A%';
 SELECT * FROM EMP WHERE DEPTNO NOT IN (10,20);
 SELECT * FROM EMP WHERE ENAME NOT LIKE 'S%';
 SELECT * FROM EMP WHERE MGR IS NOT NULL AND DEPTNO = 10;
 SELECT * FROM EMP WHERE COMM IS NULL AND JOB = 'CLERK';
 SELECT * FROM EMP WHERE MGR IS NULL AND DEPTNO NOT IN (10.30);
 
 SELECT * FROM EMP WHERE JOB = 'SALESMAN' AND DEPTNO = 30 AND SAL > 2450;
 SELECT * FROM EMP WHERE JOB = 'ANALYST' AND DEPTNO = 20 AND SAL > 2500;
 SELECT * FROM EMP WHERE ENAME LIKE 'M%' OR ENAME LIKE 'J%';
 SELECT * FROM EMP WHERE SAL*12 IS NOT NULL AND DEPTNO != 30;
 SELECT * FROM EMP WHERE ENAME NOT LIKE 'E%' OR ENAME LIKE 'R%';
 SELECT ENAME, SAL+SAL*0.10 FROM EMP WHERE MGR IS NOT NULL AND DEPTNO = 10;
 SELECT * FROM EMP WHERE JOB = 'SALESMAN' AND ENAME LIKE '%E' AND SAL LIKE '____';
 SELECT * FROM EMP WHERE HIREDATE > '1981-12-31';
 SELECT * FROM EMP WHERE HIREDATE LIKE '____-02-__';
 SELECT * FROM EMP WHERE JOB NOT IN ('MANAGER', 'CLERK') AND DEPTNO IN (10,20) AND SAL BETWEEN 1000 AND 3000;
 
 SELECT * FROM EMP WHERE SAL NOT BETWEEN 1000 AND 2000 AND JOB != 'SALESMAN' AND DEPTNO IN (10,20,30);
 SELECT DNAME FROM DEPT WHERE LOC LIKE '%O%' AND DNAME LIKE '%O%';
 SELECT * FROM EMP WHERE JOB LIKE '%MAN%';
 SELECT * FROM EMP WHERE HIREDATE BETWEEN '1983-01-01' AND '1986-12-31';
 SELECT * FROM EMP WHERE HIREDATE LIKE '%-11-%' OR '%-12-%';
 SELECT ENAME, COMM FROM EMP WHERE COMM>SAL;
 SELECT ENAME, JOB FROM EMP WHERE MGR IS NOT NULL AND ENAME LIKE 'S%';
 SELECT ENAME, SAL FROM EMP WHERE SAL*12 LIKE '%0';
 SELECT ENAME FROM EMP WHERE ENAME LIKE '%L%L%';
 SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%' OR ENAME LIKE 'E%' OR ENAME LIKE 'I%' OR ENAME LIKE 'O%' OR ENAME LIKE 'U%';
 
 SELECT ENAME FROM EMP WHERE ENAME LIKE 'A%' AND ENAME LIKE '____';
 SELECT ENAME FROM EMP WHERE ENAME LIKE 'A___';
 SELECT ENAME FROM EMP WHERE SAL LIKE '_____';
 SELECT ENAME FROM EMP WHERE ENAME LIKE '%NA%NA%';
 SELECT ENAME, SAL , COMM FROM EMP WHERE COMM IS NOT NULL AND COMM LIKE '___';
 SELECT ENAME FROM EMP WHERE ENAME LIKE '_!%' ESCAPE '!';
 SELECT * FROM EMP WHERE HIREDATE BETWEEN '1985-01-01' AND '1985-12-31' AND SAL NOT BETWEEN 1000 AND 2999;
 SELECT * FROM EMP WHERE COMM IS NULL AND ENAME LIKE '%M_';
 SELECT * FROM EMP WHERE JOB NOT IN ('SALESMAN','CLERK') AND SAL BETWEEN 1000 AND 3999;
 SELECT * FROM EMP WHERE HIREDATE LIKE '%-JUL-%';
 SELECT * FROM EMP WHERE DEPTNO IN (10,20,30) AND HIREDATE BETWEEN '1982-01-01' AND '1985-12-31';
 
 SELECT * FROM EMP WHERE ENAME LIKE '___P%';
 SELECT * FROM EMP WHERE ENAME NOT LIKE 'S%' AND COMM BETWEEN 251 AND 999;
 SELECT * FROM EMP WHERE COMM IS NULL AND ENAME LIKE '%M_';
 SELECT * FROM EMP WHERE DEPTNO IN (10,20,40) AND SAL BETWEEN 2001 AND 4000;
 SELECT * FROM EMP WHERE JOB LIKE 'CLE%' AND DEPTNO IN (10,30);
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 