SELECT * FROM SCOTT.emp;
SELECT * FROM EMP;
SELECT * FROM DEPT;
/*
ASSIGNMENT 1: QUERIES ON FROM AND SELECT CLAUSE
1. WAQTD DESIGNATION OF EMPLOYEE WHICH IS PRESENT IN EMPLOYEE TABLE.
2. WAQTD DEPARTMENT NAME ALONG WITH LOCATION OF EMPLOYEES IN EMPLOYEE TABLE.
3. WAQTD DATE OF JOINING OF EMPLOYEE IN EMPLOYEETABLE.
4. WAQTD QUARTER TERM SALARY OF ALL THE EMPLOYEES IN EMPLOYEE TABLE.
5. WAQTD ENAME,SALARY,ANNUAL SALARY WITH THE HIKE OF 25% AND 1000RS BONUS IN QUARTER SALARY FROM EMPLOYEE TABLE.
6. DISPLAY UNIQUE JOB FROM EMPLOYEE TABLE.
7. WAQTD ALL THE DETAILS OF SALGRADE TABLE.
8. WAQTD ENAME ALONG WITH THERE SALARY,ANNUALSALARY,MIDTERM SALARY, QUARTER TERM SALARY ALONG WITH SUITABLE ALIAS NAME FOR EACH OF THEM.
9. WAQTD EMPLOYEE NAME ALONG WITH THEIR SALARY AND GETTING HIKE OF 25% FROM EMPLOYEE TABLE.
10.WAQTD ENAME, SALARY, ANNUAL SALARY, 10% REDUCTION IN ANNUAL SALARY IN EMPLOYEE TABLE.
11.WAQTD EMPLOYEE NAME AND HIS EMPLOYEE NUMBER AND HIS HIRED DATE AND SALARY WITH REDUCTION OF 20% FROM EMPLOYEE TABLE. 
12.WRITE A QUERY TO DISPLAY ALL THE DETAILS OF EACH AND EVERY EMPLOYEE OF THE COMPANY.
13.WAQTD NAME OF THE EMPLOYEE, ANNUAL SALARY OF EMPLOYEE ALONG WITH THE BONUS AMOUNT 1000 RS. THEY GOT FOR DIWALI OCCASION GIVE THE PROPER ALIAS NAME FOR THE SAME.
14.WAQTD EVERY DETAIL OF DEPARTMENT PRESENT IN THE COMPANY. 
15.WAQTD NAME OF EMPLOYEE, HOW MUCH THEY ARE EARNING, WHAT DESIGNATION THEY ARE WORKING FOR, HOW MUCH COMMISSION THEY ARE GETTING FOR THEIR WORK, AT WHAT TIME THEY HAVE JOINED THE COMPANY ALSO IN WHICH DEPARTMENT NUMBER THEY ARE ASSIGNED.
*/
SELECT JOB FROM EMP;
SELECT DNAME, LOC FROM DEPT;
SELECT HIREDATE FROM EMP;
SELECT SAL*3 FROM EMP;
SELECT ENAME, SAL,SAL*12+SAL*12*0.25,SAL*3+1000 FROM EMP;
SELECT DISTINCT JOB FROM EMP;
SELECT * FROM SALGRADE; /* DOESN'T EXIXT*/
SELECT ENAME EMPNAME, SAL SALARY,SAL*12 AS ANNUAL_SALARY,SAL*6 MIDTERMSALARY,SAL*3 'QUARTER SALARY' FROM EMP;
SELECT ENAME, SAL, SAL+SAL*0.25 FROM EMP;
SELECT ENAME,SAL,SAL*12,SAL*12-SAL*12*0.20 FROM EMP;
SELECT ENAME, EMPNO, HIREDATE,SAL-SAL*0.20 FROM EMP;
SELECT * FROM EMP;
SELECT ENAME 'EMPLOYEE NAME', SAL*12+1000 AS 'DIWALI BONUS' FROM EMP;
SELECT * FROM DEPT;
SELECT ENAME, SAL, JOB, COMM,HIREDATE,DEPTNO FROM EMP;