SELECT * FROM SCOTT.emp;
/*
ASSIGNMENT 3:WHERE CLAUSE
1.WAQTD THE ANNUAL SALARY OF THE EMPLOYEE WHOS NAME IS SMITH.
2.WAQTD NAME OF THE EMPLOYEES WORKING AS CLERK. 
3.WAQTD SALARY OF THE EMPLOYEES WHO ARE WORKING AS SALESMAN.
4.WAQTD DETAILS OF THE EMP WHO EARNS MORE THAN 2000.
5.WAQTD DETAILS OF THE EMP WHOS NAME IS JONES. 
6.WAQTD DETAILS OF THE EMP WHO WAS HIRED AFTER 01-JAN-81.
7.WAQTD NAME AND SAL ALONG WITH HIS ANNUAL SALARY IF THE ANNUAL SALARY IS MORE THAN 12000. 
8.WAQTD EMPNO OF THE EMPLOYEES WHO ARE WORKING IN DEPT 30.
9.WAQTD ENAME AND HIREDATE IF THEY ARE HIRED BEFORE 1981.
10.WAQTD DETAILS OF THE EMPLOYEES WORKING AS MANAGER.
11.WAQTD NAME AND SALARY GIVEN TO AN EMPLOYEE IF EMPLOYEE EARNS A COMMISSION OF RUPEES 1400. 
12.WAQTD DETAILS OF EMPLOYEES HAVING COMMISSION MORE THAN SALARY.
13.WAQTD EMPNO OF EMPLOYEES HIRED BEFORE THE YEAR 87.
14.WAQTD DETAILS OF EMPLOYEES WORKING AS AN ANALYST
15.WAQTD DETAILS OF EMPS EARNING MORE THAN 2000 RUPEES PER MONTH.
*/
SELECT SAL*12 FROM EMP WHERE ENAME = 'SMITH';
SELECT * FROM EMP WHERE JOB='CLERK'; 
SELECT SAL FROM EMP WHERE JOB='SALESMAN';
SELECT * FROM EMP WHERE SAL>2000;
SELECT * FROM EMP WHERE ENAME='JONES';
SELECT * FROM EMP WHERE HIREDATE>1981-01-01;
SELECT ENAME, SAL, SAL*12 FROM EMP WHERE SAL*12>12000;
SELECT EMPNO FROM EMP WHERE DEPTNO=30;
SELECT ENAME, HIREDATE FROM EMP WHERE HIREDATE<1981-01-01;
SELECT * FROM EMP WHERE JOB='MANAGER';
SELECT ENAME, SAL FROM EMP WHERE COMM = 1400;
SELECT * FROM EMP WHERE COMM>SAL;
SELECT EMPNO FROM EMP WHERE HIREDATE<1987-01-01;
SELECT * FROM EMP WHERE JOB = 'ANALYST';
SELECT * FROM EMP WHERE SAL>2000; select ename, sal, sal*12, sal*6, sal* 3, comm from emp where sal> 2000;