SELECT * FROM SCOTT.emp;
SELECT * FROM SCOTT.dept;
/*
ASSIGNMENT 5: MULTI ROW FUNCTION
   1.WAQTD THE NUMBER OF EMPLOYEES WHOSE DESIGNATION IS MANAGER AND BELONGS TO DEPARTMENT 30.
   2.WAQTD THE MAXIMUM SALARY IF THEY ARE HIRED AFTER 1982.
   3.WAQTD THE AVERAGE SALARY OF THE EMPLOYEES WHO ARE HIRED IN THE MONTH OF DECEMBER.
   4.WAQTD MAXIMUM SALARY , MINIMUM SALARY OF THE EMPLOYEE WHO ARE WORKING EITHER AS ‘SALESMAN’ OR ‘ANALYST’.
   5.WAQTD THE NUMBER OF EMPLOYEE WHO ARE NOT GETTING ANY COMMISSION.
   6.WAQTD TOTAL SALARY OF THE EMPLOYEES GIVEN TO THE CLERK OF THE COMPANY.
   7.WAQTD MAXIMUM SALARY , MINIMUM SALARY OF THE EMPLOYEES WHOSE SALARY IS GREATER THAN 800 AND LESS THAN EQUAL TO 5000.
   8.WAQTD THE MAXIMUM SALARY FOR ALL THE EMPLOYEES EXCLUDING WHOSE NAME START WITH ‘S’.
   9.WAQTD THE NUMBER OF EMPLOYEE WHO DON’T HAVE A REPORTING MANAGER.
   10.WAQTD THE AVERAGE SALARY ALONG WITH TOTAL SALARY FOR THOSE EMPLOYEES WHOSE JOB IS ANALYST AND HIS NAME DO NOT END WITH ‘S’.
  
   11.WAQTD MAXIMUM SALARY , MINIMUM SALARY FOR THOSE EMPLOYEES WHO BELONG TO DEPARTMENT 10 OR 30 BUT NOT AS MANAGER.
   12.WAQTD AVERAGE SALARY , MAXIMUM SALARY IF THE EMPLOYEE NAME STARTS WITH A AND BELONGS TO DEPARTMENT 10,20,30.
   13.WAQTD THE NUMBER OF EMPLOYEES FOR THOSE EMPLOYEE WHOSE JOB IS NOT SALESMAN AND ANALYST.
   14.WAQTD THE TOTAL SALARY OF THOSE EMPLOYEE WHO ARE GETTING SOME COMMISSION AND SALARY IS LESS THAN 3000 AND MORE THAN 5000.
   15.WAQTD THE AVERAGE SALARY FOR THOSE EMPLOYEE WHOSE NAME HAS EXACTLY ONE A IN HIS NAME.
   16.WAQTD THE MAXIMUM SALARY ALONG WITH MINIMUM SALARY WHOSE DEPARTMENT IS EITHER 30,20,40 AND ARE GETTING SOME COMMISSION.
   17.WAQTD THE NUMBER OF EMPLOYEE FOR THOSE EMPLOYEES WHOSE SALARY IS GREATER THAN 1200 AND THEY ARE JOINED IN THE YEAR OF 1985.
   18.WAQTD THE AVERAGE SALARY OF ALL THE JOB EXCLUDING CLERK,MANAGER,ANALYST AND BELONGS TO DEPARTMENT 10,20.
   19.WAQTD TOTAL SALARY , MAXIMUM SALARY OF THOSE EMPLOYEES WHOSE NAME HAS 5 CHARACTERS IN HIS NAME AND BELONGS TO DEPARTMENT 20,30,40.
   20.WAQTD MINIMUM SALARY OF THOSE EMPLOYEE WHOSE COMMISSION IS GREATER THE SALARY AND BELONGS TO DEPARTMENT 10,20,30.
*/
SELECT COUNT(ENAME) FROM EMP WHERE JOB = 'MANAGER' AND DEPTNO = 30;
SELECT MAX(SAL) FROM EMP WHERE HIREDATE > '1982-12-31';
SELECT AVG(SAL) FROM EMP WHERE HIREDATE LIKE '%-12-%';
SELECT MAX(SAL), MIN(SAL) FROM EMP WHERE JOB IN ('SALESMAN','ANALYST');
SELECT COUNT(SAL) FROM EMP WHERE COMM IS NULL;
SELECT SUM(SAL) FROM EMP WHERE JOB = 'CLERK';
SELECT MAX(SAL), MIN(SAL) FROM EMP WHERE SAL BETWEEN 801 AND 5000;
SELECT MAX(SAL) FROM EMP WHERE ENAME NOT LIKE 'S%';
SELECT COUNT(*) FROM EMP WHERE MGR IS NULL;
SELECT AVG(SAL), SUM(SAL) FROM EMP WHERE JOB = 'ANALYST' AND '%S';


SELECT MAX(SAL), MIN(SAL) FROM EMP WHERE DEPTNO IN(10,30) AND JOB!='MANAGER';
SELECT AVG(SAL), MAX(SAL) FROM EMP WHERE ENAME LIKE 'A%' AND DEPTNO IN (10,20,30);
SELECT COUNT(*) FROM EMP WHERE JOB NOT IN ('SALESMAN','ANALYST');
SELECT SUM(SAL) FROM EMP WHERE COMM IS NOT NULL AND SAL NOT BETWEEN 3000 AND 5000;

SELECT * FROM EMP WHERE ENAME NOT LIKE '%A%A%';
SELECT * FROM EMP WHERE ENAME LIKE '%A%' AND ENAME NOT LIKE '%A%A%';

SELECT MAX(SAL), MIN(SAL) FROM EMP WHERE DEPTNO IN (30,20,40) AND COMM IS NOT NULL;
SELECT COUNT(*) FROM EMP WHERE SAL > 1200 AND HIREDATE LIKE '1985-%-%';
SELECT AVG(SAL) FROM EMP WHERE JOB NOT IN('CLERK', 'MANAGER','ANALYST') AND DEPTNO IN (10,20);
SELECT SUM(SAL), MAX(SAL) FROM EMP WHERE ENAME LIKE '_____' AND DEPTNO IN (20,30,40);
SELECT MIN(SAL) FROM EMP WHERE COMM > SAL AND DEPTNO IN (10,20,30);
